In [14]:
import torch


import torch.nn.functional as F
import torch.nn as nn

sample = (torch.ones(2,2))
a = torch.Tensor(2,2)
a[0,0] = 0
a[0,1] = 1
a[1,1] = 2
a[1,1] = 3
target = a

In [6]:
criterion = nn.MSELoss()
loss = criterion(sample, target)
print(loss)

tensor(1.5000)


In [7]:
samples = torch.cat((sample, sample, sample), 0)
samples

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [10]:
targets = torch.cat((a, a, sample), 0)
targets

tensor([[0., 1.],
        [0., 3.],
        [0., 1.],
        [0., 3.],
        [1., 1.],
        [1., 1.]])

In [11]:
criterion = nn.MSELoss()
loss = criterion(samples, targets)
print(loss)

tensor(1.)


In [22]:
a = torch.tensor([[1,2], [3,4], [5, 6]])
out = a*(a)
print(out)
torch.sum(out)

 
# a*a等价于a.mul(a)

tensor([[ 1,  4],
        [ 9, 16],
        [25, 36]])


tensor(91)