In [3]:
import torch
import torch.nn.functional as F

def tensor_normalize(tensor):
    if len(tensor.shape) == 1:        
        norm = F.normalize(tensor, p=1, dim=0)
    else:
        norm = F.normalize(tensor, p=1, dim=1)
    return norm

In [44]:
a = torch.arange(9, dtype= torch.float)
a = a.reshape((3,3))
print(a)
'''
tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
'''
# 对二维数组按行归一化
# p=2表示二范式, dim=1表示按行归一化

print(tensor_normalize(a))

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167],
        [0.2857, 0.3333, 0.3810]])


In [45]:
a = torch.tensor([0., 1., 2.])
print(a.shape)
b = tensor_normalize(a)
print(b)

b = F.normalize(a, p=1, dim=0)
print(b)

torch.Size([3])
tensor([0.0000, 0.3333, 0.6667])
tensor([0.0000, 0.3333, 0.6667])


In [15]:
1/5**(0.5)

0.4472135954999579

In [46]:
a= torch.tensor([-0.1483,  0.1511, -0.1298, -0.1223, -0.0070, -0.1287,  0.1493,  0.1757,
         0.1161, -0.0684])
print(tensor_normalize(a))

tensor([-0.1239,  0.1263, -0.1085, -0.1022, -0.0058, -0.1075,  0.1248,  0.1468,
         0.0970, -0.0572])


In [4]:
student_predict_score=torch.tensor([-0.2469,  0.0155,  0.0401, -0.0724, -0.0276, -0.1573, -0.1092, -0.2357,
        -0.0060, -0.0894])
the_contrastive = torch.tensor([ 0.0941, -0.1175,  0.0143, -0.0030, -0.1263, -0.1258,  0.1655,  0.2261,
        -0.0558, -0.0717])
student_contrastive_loss=torch.tensor([-0.3410,  0.1330,  0.0258, -0.0694,  0.0987, -0.0315, -0.2746, -0.4618,
         0.0498, -0.0177])


In [5]:
student_predict_score-the_contrastive

tensor([-0.3410,  0.1330,  0.0258, -0.0694,  0.0987, -0.0315, -0.2747, -0.4618,
         0.0498, -0.0177])

In [5]:
import numpy as np
import torch
a = [3.,4]
b = np.array(a)
c = torch.tensor(b, dtype=torch.float32)
c.dtype

torch.float32

In [11]:
c= torch.ones((2,3))*2
c

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [9]:
a = torch.ones((2,3))
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
c/a

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [18]:
a = 1
a = input()
print(a)

324
324
