In [1]:
import torch
import numpy as np
import torch.nn as nn
import torch.optim as optim

In [2]:
class StudentMLP(nn.Module):
    def __init__(self, size):
        super(StudentMLP, self).__init__()
        self.fc1 = nn.Linear(size, size)

    def forward(self, x):
        x = self.fc1(x)
        return x

#     权重初始化为全1,bias为0
    def initialize_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.ones_(m.weight.data)
                m.bias.data.zero_()
                print("\nafter init:  ",m) 
                print('weight is: ', m.weight)
                print(m.bias)

In [15]:
size = 3
net_list = list()
net_optimizer_set = list()
for i in range(size):
    net_list.append(StudentMLP(2))
    net_optimizer_set.append(optim.Adam(net_list[i].parameters(), lr=1, betas=(0.9, 0.999)))

In [8]:
net = StudentMLP(2)
label = torch.tensor([0., 1], requires_grad=True)
data = torch.tensor([0., 1], requires_grad=True)
print(label)
outputs = net(label)
criterion = nn.MSELoss()
a = criterion(label, outputs)
a

tensor([0., 1.], requires_grad=True)


tensor(0.9870, grad_fn=<MeanBackward0>)

In [19]:
print("the net's grad----------", net_list[0].fc1.weight.grad)
net_optimizer_set[0].zero_grad()
print("the net's grad----------", net_list[0].fc1.weight.grad)

the net's grad---------- tensor([[-3266.9119,  2461.9551],
        [ 2508.2200, -1890.2068]])
the net's grad---------- tensor([[0., 0.],
        [0., 0.]])


In [9]:
test_optimizer = optim.Adam([data], lr=1, betas=(0.9, 0.999))
test_scheduler = torch.optim.lr_scheduler.StepLR(test_optimizer, step_size=10, gamma=0.1)


In [17]:
for converge in range(100):
    tmp_loss = torch.zeros((size), dtype=torch.float32)
    
    for i in range(size):
        print("the net's grad----------", net_list[i].fc1.weight.grad)
        outputs = net_list[i](data)
        tmp_loss[i] = (criterion(label, outputs))
        print("single loss", tmp_loss[i])
    test_loss = torch.sum(tmp_loss)
    print("test loss: ", test_loss)
    test_loss.backward()
    
    test_optimizer.step()
    print("data's grad===========", data.grad)
    test_optimizer.zero_grad()
    test_scheduler.step()

the net's grad---------- None
single loss tensor(23.1348, grad_fn=<SelectBackward>)
the net's grad---------- None
single loss tensor(8.5608, grad_fn=<SelectBackward>)
the net's grad---------- None
single loss tensor(10.0918, grad_fn=<SelectBackward>)
test loss:  tensor(41.7873, grad_fn=<SumBackward0>)
data's grad=========== tensor([ 8.5140, -8.8352])
the net's grad---------- tensor([[-32.6691,  24.6196],
        [ 25.0822, -18.9021]])
single loss tensor(23.1348, grad_fn=<SelectBackward>)
the net's grad---------- tensor([[ -0.8886,   0.6696],
        [-25.0388,  18.8694]])
single loss tensor(8.5608, grad_fn=<SelectBackward>)
the net's grad---------- tensor([[ -7.6236,   5.7452],
        [ 26.1127, -19.6786]])
single loss tensor(10.0918, grad_fn=<SelectBackward>)
test loss:  tensor(41.7873, grad_fn=<SumBackward0>)
data's grad=========== tensor([ 8.5140, -8.8352])
the net's grad---------- tensor([[-65.3382,  49.2391],
        [ 50.1644, -37.8041]])
single loss tensor(23.1348, grad_fn=<Sel

the net's grad---------- tensor([[ -20.4370,   15.4014],
        [-575.8929,  433.9951]])
single loss tensor(8.5608, grad_fn=<SelectBackward>)
the net's grad---------- tensor([[-175.3424,  132.1387],
        [ 600.5914, -452.6081]])
single loss tensor(10.0918, grad_fn=<SelectBackward>)
test loss:  tensor(41.7873, grad_fn=<SumBackward0>)
data's grad=========== tensor([ 8.5140, -8.8352])
the net's grad---------- tensor([[-784.0580,  590.8694],
        [ 601.9731, -453.6491]])
single loss tensor(23.1348, grad_fn=<SelectBackward>)
the net's grad---------- tensor([[ -21.3255,   16.0710],
        [-600.9317,  452.8645]])
single loss tensor(8.5608, grad_fn=<SelectBackward>)
the net's grad---------- tensor([[-182.9660,  137.8839],
        [ 626.7041, -472.2867]])
single loss tensor(10.0918, grad_fn=<SelectBackward>)
test loss:  tensor(41.7873, grad_fn=<SumBackward0>)
data's grad=========== tensor([ 8.5140, -8.8352])
the net's grad---------- tensor([[-816.7271,  615.4890],
        [ 627.0553, -

data's grad=========== tensor([ 8.5140, -8.8352])
the net's grad---------- tensor([[-1600.7848,  1206.3582],
        [ 1229.0280,  -926.2001]])
single loss tensor(23.1348, grad_fn=<SelectBackward>)
the net's grad---------- tensor([[  -43.5397,    32.8117],
        [-1226.9022,   924.5990]])
single loss tensor(8.5608, grad_fn=<SelectBackward>)
the net's grad---------- tensor([[-373.5557,  281.5129],
        [1279.5209, -964.2515]])
single loss tensor(10.0918, grad_fn=<SelectBackward>)
test loss:  tensor(41.7873, grad_fn=<SumBackward0>)
data's grad=========== tensor([ 8.5140, -8.8352])
the net's grad---------- tensor([[-1633.4539,  1230.9777],
        [ 1254.1101,  -945.1021]])
single loss tensor(23.1348, grad_fn=<SelectBackward>)
the net's grad---------- tensor([[  -44.4282,    33.4813],
        [-1251.9410,   943.4684]])
single loss tensor(8.5608, grad_fn=<SelectBackward>)
the net's grad---------- tensor([[-381.1793,  287.2581],
        [1305.6335, -983.9301]])
single loss tensor(10.09

single loss tensor(8.5608, grad_fn=<SelectBackward>)
the net's grad---------- tensor([[ -556.5220,   419.3965],
        [ 1906.2250, -1436.5376]])
single loss tensor(10.0918, grad_fn=<SelectBackward>)
test loss:  tensor(41.7873, grad_fn=<SumBackward0>)
data's grad=========== tensor([ 8.5140, -8.8352])
the net's grad---------- tensor([[-2417.5129,  1821.8458],
        [ 1856.0818, -1398.7522]])
single loss tensor(23.1348, grad_fn=<SelectBackward>)
the net's grad---------- tensor([[  -65.7538,    49.5523],
        [-1852.8727,  1396.3336]])
single loss tensor(8.5608, grad_fn=<SelectBackward>)
the net's grad---------- tensor([[ -564.1456,   425.1416],
        [ 1932.3376, -1456.2162]])
single loss tensor(10.0918, grad_fn=<SelectBackward>)
test loss:  tensor(41.7873, grad_fn=<SumBackward0>)
data's grad=========== tensor([ 8.5140, -8.8352])
the net's grad---------- tensor([[-2450.1821,  1846.4653],
        [ 1881.1639, -1417.6543]])
single loss tensor(23.1348, grad_fn=<SelectBackward>)
the 

the net's grad---------- tensor([[  -87.9679,    66.2929],
        [-2478.8433,  1868.0682]])
single loss tensor(8.5608, grad_fn=<SelectBackward>)
the net's grad---------- tensor([[ -754.7355,   568.7706],
        [ 2585.1567, -1948.1809]])
single loss tensor(10.0918, grad_fn=<SelectBackward>)
test loss:  tensor(41.7873, grad_fn=<SumBackward0>)
data's grad=========== tensor([ 8.5140, -8.8352])


In [9]:
net = StudentMLP(2)
net.eval()
data = torch.tensor([[1, 1], [0., 1]], requires_grad=True)
print(data.grad)
print("--------", net.fc1.weight.grad)
output = net(data)
loss = torch.sum(output)

loss.backward()

print(input.grad)
print("--------", net.fc1.weight.grad)

None
-------- None
tensor([[ 58.8091,  66.5718, 110.0941],
        [ 58.8091,  66.5718, 110.0941]])
-------- tensor([[1., 2.],
        [1., 2.]])


In [12]:
featureSet_list = [1, 2]
label = torch.tensor([0., 1], requires_grad=True)


hidden_layers = list()
transferBridge_set = list()

for i in range(3):
    transferBridge_set.append(StudentMLP(2))
    hidden_layers.append(label)

    
test_common_representation = torch.tensor([0., 1], requires_grad=True)
test_optimizer = optim.Adam([test_common_representation], lr=1, betas=(0.9, 0.999))

transferBridge_criterion = nn.MSELoss()

test_loss = torch.zeros(100, dtype=torch.float32)
for converge in range(100):
    tmp_loss = torch.zeros((len(featureSet_list)), dtype=torch.float32)
    for i in range(len(featureSet_list)):
        outputs = transferBridge_set[i](test_common_representation)
        tmp_loss[i] = transferBridge_criterion(hidden_layers[i], outputs)

    test_loss[converge] = torch.sum(tmp_loss)
    print("test loss: ", test_loss)

    test_loss[converge].backward()
    test_optimizer.step()
    print(test_common_representation.grad)
    test_optimizer.zero_grad()
    print(test_common_representation.grad)


test loss:  tensor([1.6263, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000], grad_fn=<CopySlices>)
tensor([-1.2192,  1.3059])
tensor([0., 0.])
test loss:  tensor([1.626

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [11]:
featureSet_list = [1, 2]
label = torch.tensor([0., 1], requires_grad=True)


hidden_layers = list()
transferBridge_set = list()

for i in range(3):
    transferBridge_set.append(StudentMLP(2))
    hidden_layers.append(label)

    
test_common_representation = torch.tensor([0., 1], requires_grad=True)
test_optimizer = optim.Adam([test_common_representation], lr=1, betas=(0.9, 0.999))

transferBridge_criterion = nn.MSELoss()

test_loss = torch.zeros(100, dtype=torch.float32)
for converge in range(100):
    tmp_loss = torch.zeros((len(featureSet_list)), dtype=torch.float32)
    for i in range(len(featureSet_list)):
        outputs = transferBridge_set[i](test_common_representation)
        tmp_loss[i] = transferBridge_criterion(hidden_layers[i], outputs)

    test_loss[converge] = torch.sum(tmp_loss)
    print("test loss: ", test_loss)

    test_loss[converge].backward()
    test_optimizer.step()
    print(test_common_representation.grad)
    test_optimizer.zero_grad()
    print(test_common_representation.grad)
    test_scheduler.step()

test loss:  tensor([1.4790, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000], grad_fn=<CopySlices>)
tensor([-0.3488,  1.0076])
tensor([0., 0.])
test loss:  tensor([1.479

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [22]:
test_loss = torch.zeros(100, dtype=torch.float32)
test_loss

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.])

In [3]:

net.eval()
for converge in range(100):
    output = net(input)
    loss = torch.sum(output)
    loss.backward()
    print(input.grad)
    print("--------", net.weight.grad)

tensor([[1.1645, 1.3183, 2.1801],
        [1.1645, 1.3183, 2.1801]])
-------- tensor([[ 0.9221, -0.2309,  5.2201],
        [ 0.9221, -0.2309,  5.2201],
        [ 0.9221, -0.2309,  5.2201],
        [ 0.9221, -0.2309,  5.2201]])
tensor([[1.7468, 1.9774, 3.2701],
        [1.7468, 1.9774, 3.2701]])
-------- tensor([[ 1.3832, -0.3463,  7.8301],
        [ 1.3832, -0.3463,  7.8301],
        [ 1.3832, -0.3463,  7.8301],
        [ 1.3832, -0.3463,  7.8301]])
tensor([[2.3291, 2.6365, 4.3602],
        [2.3291, 2.6365, 4.3602]])
-------- tensor([[ 1.8443, -0.4617, 10.4401],
        [ 1.8443, -0.4617, 10.4401],
        [ 1.8443, -0.4617, 10.4401],
        [ 1.8443, -0.4617, 10.4401]])
tensor([[2.9113, 3.2956, 5.4502],
        [2.9113, 3.2956, 5.4502]])
-------- tensor([[ 2.3054, -0.5772, 13.0502],
        [ 2.3054, -0.5772, 13.0502],
        [ 2.3054, -0.5772, 13.0502],
        [ 2.3054, -0.5772, 13.0502]])
tensor([[3.4936, 3.9548, 6.5402],
        [3.4936, 3.9548, 6.5402]])
-------- tensor([[ 2.76

In [4]:
input

tensor([[ 0.2823,  1.3580,  0.4691],
        [-0.4066,  1.3927,  0.4474]], requires_grad=True)

In [17]:
a = torch.ones((2,3))
a.shape

torch.Size([2, 3])

In [20]:

a = torch.cat( (input,a),0 ) 
print(a)
a.shape

tensor([[ 0.2823,  1.3580,  0.4691],
        [-0.4066,  1.3927,  0.4474],
        [ 1.0000,  1.0000,  1.0000],
        [ 1.0000,  1.0000,  1.0000]], grad_fn=<CatBackward>)


torch.Size([4, 3])

In [19]:
a.cat(input, 0)
a

AttributeError: 'Tensor' object has no attribute 'cat'

In [8]:
tensor_list = list()
tensor_list.append(input)
tensor_list.append(a)
tensor_list

[tensor([[ 0.2823,  1.3580,  0.4691],
         [-0.4066,  1.3927,  0.4474]], requires_grad=True),
 tensor([[1., 1., 1.],
         [1., 1., 1.]])]

In [12]:
npa = np.array(tensor_list)

In [13]:
ttt = torch.tensor(npa)
ttt

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, int64, int32, int16, int8, and uint8.