In [1]:
import torch
import numpy as np
import torch.nn as nn
import torch.optim as optim

class StudentMLP(nn.Module):
    def __init__(self, size):
        super(StudentMLP, self).__init__()
        self.fc1 = nn.Linear(size, size)

    def forward(self, x):
        x = self.fc1(x)
        return x

#     权重初始化为全1,bias为0
    def initialize_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.ones_(m.weight.data)
                m.bias.data.zero_()
                print("\nafter init:  ",m) 
                print('weight is: ', m.weight)
                print(m.bias)

In [4]:
featureSet_list = [1, 2]
label = torch.tensor([0., 1], requires_grad=True)


hidden_layers = list()
transferBridge_set = list()

for i in range(3):
    transferBridge_set.append(StudentMLP(2))
    hidden_layers.append(label)

    
test_common_representation = torch.tensor([0., 1], requires_grad=True)
test_optimizer = optim.Adam([test_common_representation], lr=1, betas=(0.9, 0.999))

transferBridge_criterion = nn.MSELoss()

for converge in range(100):
    tmp_loss = torch.zeros((len(featureSet_list)), dtype=torch.float32)
    for i in range(len(featureSet_list)):
        outputs = transferBridge_set[i](test_common_representation)
        tmp_loss[i] = transferBridge_criterion(hidden_layers[i], outputs)

    test_loss = torch.sum(tmp_loss)
    print("test loss: ", test_loss)

    test_loss.backward()
    test_optimizer.step()
    print(test_common_representation.grad)
    test_optimizer.zero_grad()
    print(test_common_representation.grad)

test loss:  tensor(0.8440, grad_fn=<SumBackward0>)
tensor([0.4134, 0.3539])
tensor([0., 0.])
test loss:  tensor(0.6442, grad_fn=<SumBackward0>)
tensor([-0.0357, -0.3320])
tensor([0., 0.])
test loss:  tensor(0.7216, grad_fn=<SumBackward0>)
tensor([-0.2453, -0.3792])
tensor([0., 0.])
test loss:  tensor(0.6327, grad_fn=<SumBackward0>)
tensor([-0.2321, -0.1480])
tensor([0., 0.])
test loss:  tensor(0.5968, grad_fn=<SumBackward0>)
tensor([-0.1180,  0.1412])
tensor([0., 0.])
test loss:  tensor(0.6413, grad_fn=<SumBackward0>)
tensor([0.0056, 0.3215])
tensor([0., 0.])
test loss:  tensor(0.6418, grad_fn=<SumBackward0>)
tensor([0.0852, 0.3263])
tensor([0., 0.])
test loss:  tensor(0.5922, grad_fn=<SumBackward0>)
tensor([0.1062, 0.2015])
tensor([0., 0.])
test loss:  tensor(0.5590, grad_fn=<SumBackward0>)
tensor([0.0799, 0.0141])
tensor([0., 0.])
test loss:  tensor(0.5779, grad_fn=<SumBackward0>)
tensor([ 0.0315, -0.1639])
tensor([0., 0.])
test loss:  tensor(0.6119, grad_fn=<SumBackward0>)
tensor([-

In [2]:
featureSet_list = [1, 2]
label = torch.tensor([0., 1], requires_grad=True)


hidden_layers = list()
transferBridge_set = list()

for i in range(3):
    transferBridge_set.append(StudentMLP(2))
    hidden_layers.append(label)

    
test_common_representation = torch.tensor([0., 1], requires_grad=True)
test_optimizer = optim.Adam([test_common_representation], lr=1, betas=(0.9, 0.999))

transferBridge_criterion = nn.MSELoss()

test_loss = torch.zeros(100, dtype=torch.float32)
for converge in range(100):
    tmp_loss = torch.zeros((len(featureSet_list)), dtype=torch.float32)
    for i in range(len(featureSet_list)):
        outputs = transferBridge_set[i](test_common_representation)
        tmp_loss[i] = transferBridge_criterion(hidden_layers[i], outputs)

    test_loss[converge] = torch.sum(tmp_loss)
    print("test loss: ", test_loss)

    test_loss[converge].backward()
    test_optimizer.step()
    print(test_common_representation.grad)
    test_optimizer.zero_grad()
    print(test_common_representation.grad)


test loss:  tensor([0.5663, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000], grad_fn=<CopySlices>)
tensor([-0.3490, -0.2414])
tensor([0., 0.])
test loss:  tensor([0.566

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [3]:
featureSet_list = [1, 2]

label = torch.tensor([0., 1], requires_grad=True)

hidden_layers = list()
transferBridge_set = list()

for i in range(3):
    transferBridge_set.append(StudentMLP(2))
    hidden_layers.append(label)

    
test_common_representation = torch.tensor([0., 1], requires_grad=True)
test_optimizer = optim.Adam([test_common_representation], lr=1, betas=(0.9, 0.999))

transferBridge_criterion = nn.MSELoss()


for converge in range(100):
    tmp_loss = torch.zeros((len(featureSet_list)), dtype=torch.float32)
    for i in range(len(featureSet_list)):
        outputs = transferBridge_set[i](test_common_representation)
        tmp_loss[i] = transferBridge_criterion(hidden_layers[i], outputs)
    
#     test_loss = None

    test_loss = torch.sum(tmp_loss)
    print("test loss: ", test_loss)

#     test_loss.backward(retain_graph=True)
    test_loss.backward()
    test_optimizer.step()
    print(test_loss)
    test_optimizer.zero_grad()


test loss:  tensor(3.6152, grad_fn=<SumBackward0>)
tensor(3.6152, grad_fn=<SumBackward0>)
test loss:  tensor(0.9550, grad_fn=<SumBackward0>)
tensor(0.9550, grad_fn=<SumBackward0>)
test loss:  tensor(0.8780, grad_fn=<SumBackward0>)
tensor(0.8780, grad_fn=<SumBackward0>)
test loss:  tensor(1.5786, grad_fn=<SumBackward0>)
tensor(1.5786, grad_fn=<SumBackward0>)
test loss:  tensor(1.6144, grad_fn=<SumBackward0>)
tensor(1.6144, grad_fn=<SumBackward0>)
test loss:  tensor(1.1092, grad_fn=<SumBackward0>)
tensor(1.1092, grad_fn=<SumBackward0>)
test loss:  tensor(0.5799, grad_fn=<SumBackward0>)
tensor(0.5799, grad_fn=<SumBackward0>)
test loss:  tensor(0.3740, grad_fn=<SumBackward0>)
tensor(0.3740, grad_fn=<SumBackward0>)
test loss:  tensor(0.5259, grad_fn=<SumBackward0>)
tensor(0.5259, grad_fn=<SumBackward0>)
test loss:  tensor(0.8011, grad_fn=<SumBackward0>)
tensor(0.8011, grad_fn=<SumBackward0>)
test loss:  tensor(0.9335, grad_fn=<SumBackward0>)
tensor(0.9335, grad_fn=<SumBackward0>)
test loss: