In [7]:
import torch
import numpy as np

common_representation = torch.rand((10, 64), device="cuda:1", requires_grad=True)
common_representation

tensor([[6.8820e-01, 9.9297e-01, 3.1351e-01, 5.6502e-01, 2.0037e-01, 8.0454e-02,
         4.6799e-01, 1.2498e-01, 1.8547e-03, 6.4904e-01, 7.4151e-01, 6.4282e-01,
         4.2408e-01, 9.4463e-01, 5.6679e-01, 7.2566e-01, 5.8910e-01, 8.1234e-01,
         1.9042e-01, 2.5821e-01, 3.5868e-01, 6.5641e-01, 4.3225e-01, 2.0521e-01,
         2.0250e-02, 2.9513e-01, 9.9339e-01, 5.3574e-01, 8.9091e-01, 7.5673e-01,
         2.3322e-02, 2.0763e-01, 2.5927e-01, 5.1485e-01, 1.2754e-01, 5.6282e-01,
         1.6700e-01, 3.7859e-03, 9.8381e-01, 3.6272e-01, 3.8134e-02, 7.9890e-01,
         9.4220e-01, 8.4213e-01, 8.1733e-01, 4.2484e-01, 1.8723e-01, 5.0708e-01,
         7.7804e-01, 4.2672e-01, 8.8863e-01, 9.2107e-01, 2.3684e-01, 9.6457e-01,
         8.8873e-01, 1.5605e-01, 7.7301e-01, 7.5744e-01, 8.8920e-01, 2.4046e-01,
         7.2839e-01, 4.7256e-01, 5.7164e-01, 2.7568e-01],
        [6.6000e-01, 6.4508e-01, 1.9800e-01, 8.3322e-01, 3.2761e-01, 3.1916e-01,
         9.1082e-01, 8.7850e-01, 6.9639e-01, 7.0291

In [8]:
np_common_representation = common_representation.detach().cpu().numpy()
np_common_representation


array([[6.88199937e-01, 9.92970288e-01, 3.13510746e-01, 5.65021813e-01,
        2.00365260e-01, 8.04541856e-02, 4.67987567e-01, 1.24983177e-01,
        1.85468758e-03, 6.49041414e-01, 7.41513669e-01, 6.42819047e-01,
        4.24081951e-01, 9.44627762e-01, 5.66792607e-01, 7.25655854e-01,
        5.89097321e-01, 8.12338233e-01, 1.90422222e-01, 2.58214355e-01,
        3.58682394e-01, 6.56406701e-01, 4.32251155e-01, 2.05205992e-01,
        2.02504806e-02, 2.95127749e-01, 9.93394017e-01, 5.35739720e-01,
        8.90912712e-01, 7.56731689e-01, 2.33220514e-02, 2.07631722e-01,
        2.59273320e-01, 5.14853179e-01, 1.27544329e-01, 5.62817395e-01,
        1.67001978e-01, 3.78592033e-03, 9.83814061e-01, 3.62715364e-01,
        3.81340459e-02, 7.98896730e-01, 9.42203939e-01, 8.42131436e-01,
        8.17326844e-01, 4.24841315e-01, 1.87231854e-01, 5.07075906e-01,
        7.78038800e-01, 4.26720947e-01, 8.88630390e-01, 9.21072543e-01,
        2.36837149e-01, 9.64574337e-01, 8.88727605e-01, 1.560541

In [10]:
test_data_path = "./tensor.npy"
np.save(test_data_path, np_common_representation)

In [12]:
test_data = np.load(test_data_path)
test_data

array([[6.88199937e-01, 9.92970288e-01, 3.13510746e-01, 5.65021813e-01,
        2.00365260e-01, 8.04541856e-02, 4.67987567e-01, 1.24983177e-01,
        1.85468758e-03, 6.49041414e-01, 7.41513669e-01, 6.42819047e-01,
        4.24081951e-01, 9.44627762e-01, 5.66792607e-01, 7.25655854e-01,
        5.89097321e-01, 8.12338233e-01, 1.90422222e-01, 2.58214355e-01,
        3.58682394e-01, 6.56406701e-01, 4.32251155e-01, 2.05205992e-01,
        2.02504806e-02, 2.95127749e-01, 9.93394017e-01, 5.35739720e-01,
        8.90912712e-01, 7.56731689e-01, 2.33220514e-02, 2.07631722e-01,
        2.59273320e-01, 5.14853179e-01, 1.27544329e-01, 5.62817395e-01,
        1.67001978e-01, 3.78592033e-03, 9.83814061e-01, 3.62715364e-01,
        3.81340459e-02, 7.98896730e-01, 9.42203939e-01, 8.42131436e-01,
        8.17326844e-01, 4.24841315e-01, 1.87231854e-01, 5.07075906e-01,
        7.78038800e-01, 4.26720947e-01, 8.88630390e-01, 9.21072543e-01,
        2.36837149e-01, 9.64574337e-01, 8.88727605e-01, 1.560541