In [1]:
import numpy as np
import torch
import os
import sys
import random
from PIL import Image
from torch.utils.data import Dataset

DATASIZE = 2000
# !!!如果改变此参数,split_datasets中的也需要改
TRAIN_PRECENT = 0.8
CLASS_NUM = 10


class handWritten_Dataset(Dataset):
    def __init__(self, data_path, transform=None, train=True):
        """
        mfeat-fou的Dataset
        :param data_path: str, 数据集所在路径
        :param transform: torch.transform，数据预处理
        """

        self.label_name = {"0": 0, "1": 1}
        self.class_size = self.get_class_size(train)
        self.data_info = self.get_img_info(data_path)
        self.transform = transform


    def __getitem__(self, index):
        data, label = self.data_info[index]

        if self.transform is not None:
            data = self.transform(data)

        return data, label, index

    def __len__(self):
        return len(self.data_info)

    # @staticmethod
    def get_class_size(self, train):
        class_size = int(DATASIZE*TRAIN_PRECENT/CLASS_NUM)
        if not train:
            class_size = 200 - class_size
        return class_size

    # @staticmethod
    def get_img_info(self, file_path):
        data_info = list()
        train_data = np.load(file_path)
        for i, data in enumerate(train_data):
            label = int(i / self.class_size)
            data_info.append((data, label))

        # print(data_info[0])
        return data_info

    def get_features_size(self):
        return len(self.data_info[0][0])




## 创建一个规律的dataset,以便观察

In [2]:
dataset = [[i] for i in range(1600)]
dataset = np.array(dataset)

mydataset_path = './mydataset.npy' 
np.save(mydataset_path, dataset)

dataset = torch.tensor(dataset).to("cuda:0")
print(dataset)

tensor([[   0],
        [   1],
        [   2],
        ...,
        [1597],
        [1598],
        [1599]], device='cuda:0')


In [3]:
file_name = 'mfeat-zer'
# train_file_path = '../datasets/Handwritten/mfeat/splite/' + file_name + '/train_data.npy'
train_file_path = mydataset_path

In [4]:
train_data = handWritten_Dataset(data_path=train_file_path)
train_loader = torch.utils.data.DataLoader(dataset=train_data, batch_size=2, shuffle=True)

In [6]:
# total = torch.tensor()

count = 2
for i, data in enumerate(train_loader):
    print("# ============================ the {} data".format(i))
    print(data)
    
    _, _, index = data
    
    index.to("cuda:0")
    print("get reconstruct represesnetation")
#     print(dataset[index.numpy()])
    print(dataset[index])

    if i > count:
        break

# ============================ the 0 data
[tensor([[ 361],
        [1536]]), tensor([2, 9]), tensor([ 361, 1536])]
get reconstruct represesnetation
tensor([[ 361],
        [1536]], device='cuda:0')
# ============================ the 1 data
[tensor([[ 458],
        [1307]]), tensor([2, 8]), tensor([ 458, 1307])]
get reconstruct represesnetation
tensor([[ 458],
        [1307]], device='cuda:0')
# ============================ the 2 data
[tensor([[425],
        [170]]), tensor([2, 1]), tensor([425, 170])]
get reconstruct represesnetation
tensor([[425],
        [170]], device='cuda:0')
# ============================ the 3 data
[tensor([[678],
        [856]]), tensor([4, 5]), tensor([678, 856])]
get reconstruct represesnetation
tensor([[678],
        [856]], device='cuda:0')


In [8]:
# total = torch.tensor()

count = 4
for i, data in enumerate(train_loader):
    print("# ============================ the {} data".format(i))
    print(data[2])
    _, _, index = data
    print(index)
    
  

# ============================ the 0 data
tensor([354, 564])
tensor([354, 564])
# ============================ the 1 data
tensor([949, 783])
tensor([949, 783])
# ============================ the 2 data
tensor([  2, 866])
tensor([  2, 866])
# ============================ the 3 data
tensor([ 384, 1546])
tensor([ 384, 1546])
# ============================ the 4 data
tensor([1136, 1225])
tensor([1136, 1225])
# ============================ the 5 data
tensor([1033,  529])
tensor([1033,  529])
# ============================ the 6 data
tensor([ 511, 1030])
tensor([ 511, 1030])
# ============================ the 7 data
tensor([1192,  891])
tensor([1192,  891])
# ============================ the 8 data
tensor([1159,  952])
tensor([1159,  952])
# ============================ the 9 data
tensor([443, 249])
tensor([443, 249])
# ============================ the 10 data
tensor([ 725, 1302])
tensor([ 725, 1302])
# ============================ the 11 data
tensor([302, 513])
tensor([302, 513])
# ========

# ============================ the 240 data
tensor([1516, 1245])
tensor([1516, 1245])
# ============================ the 241 data
tensor([531, 477])
tensor([531, 477])
# ============================ the 242 data
tensor([1558,  408])
tensor([1558,  408])
# ============================ the 243 data
tensor([1579,  147])
tensor([1579,  147])
# ============================ the 244 data
tensor([ 334, 1087])
tensor([ 334, 1087])
# ============================ the 245 data
tensor([1375,  741])
tensor([1375,  741])
# ============================ the 246 data
tensor([1505,   71])
tensor([1505,   71])
# ============================ the 247 data
tensor([460, 190])
tensor([460, 190])
# ============================ the 248 data
tensor([1236, 1300])
tensor([1236, 1300])
# ============================ the 249 data
tensor([812, 319])
tensor([812, 319])
# ============================ the 250 data
tensor([1396,  931])
tensor([1396,  931])
# ============================ the 251 data
tensor([227, 428])
ten

# ============================ the 460 data
tensor([797, 991])
tensor([797, 991])
# ============================ the 461 data
tensor([ 405, 1536])
tensor([ 405, 1536])
# ============================ the 462 data
tensor([ 583, 1595])
tensor([ 583, 1595])
# ============================ the 463 data
tensor([332,   4])
tensor([332,   4])
# ============================ the 464 data
tensor([1023,  195])
tensor([1023,  195])
# ============================ the 465 data
tensor([484, 196])
tensor([484, 196])
# ============================ the 466 data
tensor([825, 867])
tensor([825, 867])
# ============================ the 467 data
tensor([251,  77])
tensor([251,  77])
# ============================ the 468 data
tensor([1458, 1497])
tensor([1458, 1497])
# ============================ the 469 data
tensor([524, 565])
tensor([524, 565])
# ============================ the 470 data
tensor([414, 142])
tensor([414, 142])
# ============================ the 471 data
tensor([556, 244])
tensor([556, 244])


tensor([1492, 1057])
# ============================ the 705 data
tensor([1547,  860])
tensor([1547,  860])
# ============================ the 706 data
tensor([1350, 1452])
tensor([1350, 1452])
# ============================ the 707 data
tensor([1091,  648])
tensor([1091,  648])
# ============================ the 708 data
tensor([999, 420])
tensor([999, 420])
# ============================ the 709 data
tensor([1182,   17])
tensor([1182,   17])
# ============================ the 710 data
tensor([ 975, 1382])
tensor([ 975, 1382])
# ============================ the 711 data
tensor([ 630, 1387])
tensor([ 630, 1387])
# ============================ the 712 data
tensor([1293,   55])
tensor([1293,   55])
# ============================ the 713 data
tensor([1107,  900])
tensor([1107,  900])
# ============================ the 714 data
tensor([743,  37])
tensor([743,  37])
# ============================ the 715 data
tensor([ 966, 1124])
tensor([ 966, 1124])
# ============================ the 716 da

In [14]:
arr2 = np.array([[7,8,9], [10,11,12]])
data = np.empty((2,3), dtype = int) 
print(data)


[[ 7  8  9]
 [10 11 12]]


In [15]:
data = np.empty((2,3), dtype = int) 
print(data)

[[ 7  8  9]
 [10 11 12]]


In [12]:

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8,9], [10,11,12]])
data = np.empty(arr2.shape, dtype = int) 
print(data)
data = np.concatenate([data, arr2], axis=0) # axis参数指明合并的轴向，0表示按行，1表示按列
print(data.shape)
data

[[ 7  8  9]
 [10 11 12]]
(4, 3)


array([[ 7,  8,  9],
       [10, 11, 12],
       [ 7,  8,  9],
       [10, 11, 12]])

In [61]:
data = np.concatenate([data, arr2], axis=0) # axis参数指明合并的轴向，0表示按行，1表示按列
data

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 7,  8,  9],
       [10, 11, 12]])